### ISSUE TITLE
Updating Readme.md with some more Output Images

### ISSUE THREAD

**Issue by SAITARUN55** [NJACKWinterOfCode/FlutterSpace#12]
Will be working again on this issue @rkishan516 bro...by the end of the day I will make a PR soon...

**Comment by rkishan516** [comment]
@SAITARUN55 sorry, but there is already an issue with same context #3 .So, it's not a legitimate issue.

**Comment by SAITARUN55** [comment]
Okay but after making changes...do I need to raise another PR or?

**Comment by rkishan516** [comment]
Ya, you have to open a new PR. Please try to improve the image quality.

**Comment by SAITARUN55** [comment]
Okay...i had taken screenshots 😅...it would be great if you have any other idea...for a better quality of images🤔
