### ISSUE TITLE
Add GitHub Action Continuous Integration Script for app build

### ISSUE THREAD

**Issue by rkishan516** [NJACKWinterOfCode/FlutterSpace#4]
Add GitHub Action Continuous Integration Script for app build

**Comment by InfiniteVerma** [comment]
I'll like to work on this

**Comment by rkishan516** [comment]
@InfiniteVerma Sure, you can.

**Comment by InfiniteVerma** [comment]
Do you want the script to work for both push and pr?

**Comment by rkishan516** [comment]
@InfiniteVerma Yes.

**Comment by rkishan516** [comment]
Fixed in #9
